name: Schedule Notebook Execution

on:
  push:
  schedule:
    - cron: '* * * * *'

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install papermill
        pip install ipykernel
        python -m ipykernel install --user --name python3 --display-name "Python 3"

    - name: Execute Notebook
      run: |
        papermill notebook.ipynb output.ipynb
