name: Schedule Notebook Execution

on:
  push:
  schedule:
    - cron: '* * * * *'

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Set up Node 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install papermill

    - name: Execute Notebook
      run: |
        papermill review.ipynb output.ipynb -k 'python' -p foo bar
